In [9]:
import numpy as np

a = np.array([0,1,2,3])  #a vector
b = np.array([4,5,6,7])  #a vector
c = np.array([[0,1,2,3], #a matrix
              [4,5,6,7]
            ])

d = np.zeros((2,4)) # 2x4 zero matrix
e = np.random.randint(100,size=(2,5)) #random 2x5 matrix with all entries less than 100
f = np.random.rand(2,5) #random 2x5 matrix with all entries less than 1.

In [11]:
print(a,b,c,d,e,f,sep='\n')

[0 1 2 3]
[4 5 6 7]
[[0 1 2 3]
 [4 5 6 7]]
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[76 12 70 34 57]
 [71 94  1 29 22]]
[[0.26355964 0.66042985 0.6056391  0.32089444 0.14451105]
 [0.95330417 0.72344484 0.34788678 0.05668917 0.96232076]]


In [12]:
print(a*0.1)
print(a*b) 

[0.  0.1 0.2 0.3]
[ 0  5 12 21]


In [15]:
a = np.zeros((1,4))
b = np.zeros((4,3))

c = a.dot(b) #if arrays are 2D, np.dot result matrix multiplication
             # else vector dot product

print(c.shape)

(1, 3)


In [ ]:
d = np.zeros((5,4)).T #.T for transpose