In [11]:
import numpy as np

In [12]:
a = np.array([[
        [[[1,2,3],[1,2,3],[1,2,3]]],
        [[[1,2,3],[1,2,3],[1,2,3]]],
        [[[1,2,3],[1,2,3],[1,2,3]]]
    ],[
       [[[1,2,3],[1,2,3],[1,2,3]]],
        [[[1,2,3],[1,2,3],[1,2,3]]],
        [[[1,2,3],[1,2,3],[1,2,3]]]
    ]])

b= np.concatenate(a,axis=1)
print(a.shape,b.shape)
print(b)

(2, 3, 1, 3, 3) (3, 2, 3, 3)
[[[[1 2 3]
   [1 2 3]
   [1 2 3]]

  [[1 2 3]
   [1 2 3]
   [1 2 3]]]


 [[[1 2 3]
   [1 2 3]
   [1 2 3]]

  [[1 2 3]
   [1 2 3]
   [1 2 3]]]


 [[[1 2 3]
   [1 2 3]
   [1 2 3]]

  [[1 2 3]
   [1 2 3]
   [1 2 3]]]]
