In [21]:
import numpy as np

a = np.random.randint(5,size=(3,2,1,3,3))
b = np.concatenate(a,axis =1)
print(a.shape,b.shape)
print(a,b,sep="\n#####\n")
es = b.shape
f = b.reshape(es[0]*es[1],-1)
print(f)

(3, 2, 1, 3, 3) (2, 3, 3, 3)
[[[[[2 3 0]
    [4 2 4]
    [0 2 4]]]


  [[[3 0 0]
    [2 0 0]
    [0 1 4]]]]



 [[[[3 4 4]
    [4 3 1]
    [2 4 3]]]


  [[[4 2 3]
    [2 2 0]
    [0 0 3]]]]



 [[[[0 3 3]
    [2 0 4]
    [3 4 1]]]


  [[[3 2 1]
    [3 4 0]
    [4 2 0]]]]]
#####
[[[[2 3 0]
   [4 2 4]
   [0 2 4]]

  [[3 4 4]
   [4 3 1]
   [2 4 3]]

  [[0 3 3]
   [2 0 4]
   [3 4 1]]]


 [[[3 0 0]
   [2 0 0]
   [0 1 4]]

  [[4 2 3]
   [2 2 0]
   [0 0 3]]

  [[3 2 1]
   [3 4 0]
   [4 2 0]]]]
[[2 3 0 4 2 4 0 2 4]
 [3 4 4 4 3 1 2 4 3]
 [0 3 3 2 0 4 3 4 1]
 [3 0 0 2 0 0 0 1 4]
 [4 2 3 2 2 0 0 0 3]
 [3 2 1 3 4 0 4 2 0]]
