In [7]:
import numpy as np

weights = np.array([0.5, 0.48, -0.7])
alpha = 0.1

streetlights = np.array([
    [1,0,1],
    [0,1,1],
    [0,0,1],
    [1,1,1],
    [0,1,1],
    [1,0,1]
])

In [8]:
walk_vs_stop = np.array([0,1,0,1,1,0])

input = streetlights[0]
goal_pred = walk_vs_stop[0]

for iter in range(4):
    pred = input.dot(weights)
    error = (pred - goal_pred)**2
    delta = pred - goal_pred
    weight_delta = delta*input
    weights -= weight_delta*alpha

    print('----')
    print(f'{iter} Error: {error} Pred: {pred} Goal: {goal_pred}')

----
0 Error: 0.03999999999999998 Pred: -0.19999999999999996 Goal: 0
[-0.2 -0.  -0.2]
----
1 Error: 0.025599999999999973 Pred: -0.15999999999999992 Goal: 0
[-0.16 -0.   -0.16]
----
2 Error: 0.01638399999999997 Pred: -0.1279999999999999 Goal: 0
[-0.128 -0.    -0.128]
----
3 Error: 0.010485759999999964 Pred: -0.10239999999999982 Goal: 0
[-0.1024 -0.     -0.1024]
